<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @version 0.2b
 */

//
// Database "kbb"
//

// kbb.Model
$Model = array(
  array('ModelId'=>'8','DisplayName'=>'A6','Description'=>'','MakeId'=>'4','SortOrder'=>'9','MarketName'=>'','ShortName'=>'A6'),
  array('ModelId'=>'12','DisplayName'=>'3 Series','Description'=>'','MakeId'=>'5','SortOrder'=>'0','MarketName'=>'','ShortName'=>'3 Series'),
  array('ModelId'=>'45','DisplayName'=>'Corvette','Description'=>'','MakeId'=>'9','SortOrder'=>'44','MarketName'=>'','ShortName'=>'Corvette'),
  array('ModelId'=>'46','DisplayName'=>'Impala','Description'=>'','MakeId'=>'9','SortOrder'=>'63','MarketName'=>'','ShortName'=>'Impala'),
  array('ModelId'=>'49','DisplayName'=>'Malibu','Description'=>'','MakeId'=>'9','SortOrder'=>'69','MarketName'=>'','ShortName'=>'Malibu'),
  array('ModelId'=>'68','DisplayName'=>'300','Description'=>'','MakeId'=>'10','SortOrder'=>'2','MarketName'=>'300','ShortName'=>'300'),
  array('ModelId'=>'72','DisplayName'=>'Sebring','Description'=>'','MakeId'=>'10','SortOrder'=>'18','MarketName'=>'','ShortName'=>'Sebring'),
  array('ModelId'=>'77','DisplayName'=>'Magnum','Description'=>'','MakeId'=>'13','SortOrder'=>'32','MarketName'=>'','ShortName'=>'Magnum'),
  array('ModelId'=>'92','DisplayName'=>'GT','Description'=>'','MakeId'=>'15','SortOrder'=>'85','MarketName'=>'','ShortName'=>'GT'),
  array('ModelId'=>'93','DisplayName'=>'Mustang','Description'=>'','MakeId'=>'15','SortOrder'=>'86','MarketName'=>'','ShortName'=>'Mustang'),
  array('ModelId'=>'94','DisplayName'=>'Taurus','Description'=>'','MakeId'=>'15','SortOrder'=>'93','MarketName'=>'','ShortName'=>'Taurus'),
  array('ModelId'=>'100','DisplayName'=>'Explorer','Description'=>'','MakeId'=>'15','SortOrder'=>'38','MarketName'=>'','ShortName'=>'Explorer'),
  array('ModelId'=>'122','DisplayName'=>'Accord','Description'=>'','MakeId'=>'18','SortOrder'=>'1','MarketName'=>'','ShortName'=>'Accord'),
  array('ModelId'=>'123','DisplayName'=>'Civic','Description'=>'','MakeId'=>'18','SortOrder'=>'3','MarketName'=>'','ShortName'=>'Civic'),
  array('ModelId'=>'138','DisplayName'=>'Sonata','Description'=>'','MakeId'=>'20','SortOrder'=>'11','MarketName'=>'','ShortName'=>'Sonata'),
  array('ModelId'=>'162','DisplayName'=>'Grand Cherokee','Description'=>'','MakeId'=>'24','SortOrder'=>'13','MarketName'=>'','ShortName'=>'Grand Cherokee'),
  array('ModelId'=>'164','DisplayName'=>'Wrangler','Description'=>'','MakeId'=>'24','SortOrder'=>'16','MarketName'=>'','ShortName'=>'Wrangler'),
  array('ModelId'=>'213','DisplayName'=>'E-Class','Description'=>'','MakeId'=>'31','SortOrder'=>'29','MarketName'=>'','ShortName'=>'E-Class'),
  array('ModelId'=>'215','DisplayName'=>'S-Class','Description'=>'','MakeId'=>'31','SortOrder'=>'35','MarketName'=>'','ShortName'=>'S-Class'),
  array('ModelId'=>'234','DisplayName'=>'350Z','Description'=>'','MakeId'=>'35','SortOrder'=>'4','MarketName'=>'','ShortName'=>'350Z'),
  array('ModelId'=>'236','DisplayName'=>'Altima','Description'=>'','MakeId'=>'35','SortOrder'=>'6','MarketName'=>'','ShortName'=>'Altima'),
  array('ModelId'=>'244','DisplayName'=>'Quest','Description'=>'','MakeId'=>'35','SortOrder'=>'28','MarketName'=>'','ShortName'=>'Quest'),
  array('ModelId'=>'254','DisplayName'=>'911','Description'=>'','MakeId'=>'41','SortOrder'=>'1','MarketName'=>'','ShortName'=>'911'),
  array('ModelId'=>'257','DisplayName'=>'9-3','Description'=>'','MakeId'=>'43','SortOrder'=>'1','MarketName'=>'','ShortName'=>'9-3'),
  array('ModelId'=>'262','DisplayName'=>'9-5','Description'=>'','MakeId'=>'43','SortOrder'=>'3','MarketName'=>'','ShortName'=>'9-5'),
  array('ModelId'=>'276','DisplayName'=>'Legacy','Description'=>'','MakeId'=>'47','SortOrder'=>'15','MarketName'=>'','ShortName'=>'Legacy'),
  array('ModelId'=>'295','DisplayName'=>'Highlander','Description'=>'','MakeId'=>'49','SortOrder'=>'9','MarketName'=>'','ShortName'=>'Highlander'),
  array('ModelId'=>'299','DisplayName'=>'Sienna','Description'=>'','MakeId'=>'49','SortOrder'=>'20','MarketName'=>'','ShortName'=>'Sienna'),
  array('ModelId'=>'318','DisplayName'=>'CL','Description'=>'','MakeId'=>'2','SortOrder'=>'0','MarketName'=>'','ShortName'=>'CL'),
  array('ModelId'=>'320','DisplayName'=>'XC90','Description'=>'','MakeId'=>'51','SortOrder'=>'23','MarketName'=>'','ShortName'=>'XC90'),
  array('ModelId'=>'325','DisplayName'=>'Z8','Description'=>'','MakeId'=>'5','SortOrder'=>'0','MarketName'=>'','ShortName'=>'Z8'),
  array('ModelId'=>'426','DisplayName'=>'Avenger','Description'=>'','MakeId'=>'13','SortOrder'=>'1','MarketName'=>'','ShortName'=>'Avenger'),
  array('ModelId'=>'516','DisplayName'=>'Defender 90','Description'=>'','MakeId'=>'26','SortOrder'=>'1','MarketName'=>'','ShortName'=>'Defender 90'),
  array('ModelId'=>'786','DisplayName'=>'Silverado 2500 HD Extended Cab','Description'=>'','MakeId'=>'9','SortOrder'=>'99','MarketName'=>'Silverado 2500','ShortName'=>'Silverado 2500HD Ext Cab'),
  array('ModelId'=>'787','DisplayName'=>'Silverado 2500 HD Crew Cab','Description'=>'','MakeId'=>'9','SortOrder'=>'98','MarketName'=>'Silverado 2500','ShortName'=>'Silverado 2500HD Crew Cab'),
  array('ModelId'=>'789','DisplayName'=>'Silverado 2500 HD Regular Cab','Description'=>'','MakeId'=>'9','SortOrder'=>'100','MarketName'=>'Silverado 2500','ShortName'=>'Silverado 2500HD Reg Cab'),
  array('ModelId'=>'840','DisplayName'=>'F150 Super Cab','Description'=>'','MakeId'=>'15','SortOrder'=>'47','MarketName'=>'F150','ShortName'=>'F150 Super Cab'),
  array('ModelId'=>'869','DisplayName'=>'XK Series','Description'=>'','MakeId'=>'23','SortOrder'=>'15','MarketName'=>'','ShortName'=>'XK Series'),
  array('ModelId'=>'877','DisplayName'=>'Sprinter 2500 Passenger','Description'=>'','MakeId'=>'13','SortOrder'=>'80','MarketName'=>'Sprinter','ShortName'=>'Sprinter 2500 Passenger'),
  array('ModelId'=>'880','DisplayName'=>'Frontier Crew Cab','Description'=>'','MakeId'=>'35','SortOrder'=>'11','MarketName'=>'Frontier','ShortName'=>'Frontier Crew Cab'),
  array('ModelId'=>'924','DisplayName'=>'RS 4','Description'=>'','MakeId'=>'4','SortOrder'=>'18','MarketName'=>'','ShortName'=>'RS 4'),
  array('ModelId'=>'959','DisplayName'=>'Sprinter 2500 Cab & Chassis','Description'=>'','MakeId'=>'13','SortOrder'=>'78','MarketName'=>'Sprinter','ShortName'=>'Sprinter 2500 C&C'),
  array('ModelId'=>'968','DisplayName'=>'F550 Super Duty Regular Cab & Chassis','Description'=>'','MakeId'=>'15','SortOrder'=>'74','MarketName'=>'F550','ShortName'=>'F550 Super Duty Reg C&C'),
  array('ModelId'=>'969','DisplayName'=>'F450 Super Duty Crew Cab & Chassis','Description'=>'','MakeId'=>'15','SortOrder'=>'69','MarketName'=>'F450','ShortName'=>'F450 Super Duty Crew C&C'),
  array('ModelId'=>'971','DisplayName'=>'Silverado 2500 Extended Cab','Description'=>'','MakeId'=>'9','SortOrder'=>'97','MarketName'=>'Silverado 2500','ShortName'=>'Silverado 2500 Ext Cab'),
  array('ModelId'=>'973','DisplayName'=>'F450 Super Duty Super Cab & Chassis','Description'=>'','MakeId'=>'15','SortOrder'=>'71','MarketName'=>'F450','ShortName'=>'F450 Super Duty Super C&C'),
  array('ModelId'=>'975','DisplayName'=>'F550 Super Duty Crew Cab & Chassis','Description'=>'','MakeId'=>'15','SortOrder'=>'73','MarketName'=>'F550','ShortName'=>'F550 Super Duty Crew C&C'),
  array('ModelId'=>'976','DisplayName'=>'F550 Super Duty Super Cab & Chassis','Description'=>'','MakeId'=>'15','SortOrder'=>'75','MarketName'=>'F550','ShortName'=>'F550 Super Duty Super C&C'),
  array('ModelId'=>'980','DisplayName'=>'Silverado 2500 Regular Cab','Description'=>'','MakeId'=>'9','SortOrder'=>'102','MarketName'=>'Silverado 2500','ShortName'=>'Silverado 2500 Reg Cab'),
  array('ModelId'=>'987','DisplayName'=>'E350 Super Duty Cutaway','Description'=>'','MakeId'=>'15','SortOrder'=>'19','MarketName'=>'E350','ShortName'=>'E350 Super Duty Cutaway'),
  array('ModelId'=>'990','DisplayName'=>'Colorado Regular Cab & Chassis','Description'=>'','MakeId'=>'9','SortOrder'=>'42','MarketName'=>'Colorado','ShortName'=>'Colorado Regular C&C'),
  array('ModelId'=>'992','DisplayName'=>'Sierra 3500 Extended Cab & Chassis','Description'=>'','MakeId'=>'16','SortOrder'=>'84','MarketName'=>'Sierra 3500','ShortName'=>'Sierra 3500 Extended C&C'),
  array('ModelId'=>'993','DisplayName'=>'Sierra 3500 Regular Cab & Chassis','Description'=>'','MakeId'=>'16','SortOrder'=>'93','MarketName'=>'Sierra 3500','ShortName'=>'Sierra 3500 Regular C&C'),
  array('ModelId'=>'994','DisplayName'=>'Silverado 3500 Extended Cab & Chassis','Description'=>'','MakeId'=>'9','SortOrder'=>'108','MarketName'=>'Silverado 3500','ShortName'=>'Silverado 3500 Ext C&C'),
  array('ModelId'=>'996','DisplayName'=>'Silverado 3500 Regular Cab & Chassis','Description'=>'','MakeId'=>'9','SortOrder'=>'117','MarketName'=>'Silverado 3500','ShortName'=>'Silverado 3500 Reg C&C'),
  array('ModelId'=>'10081','DisplayName'=>'Ram 3500 Regular Cab & Chassis','Description'=>'','MakeId'=>'13','SortOrder'=>'58','MarketName'=>'Ram 3500','ShortName'=>'Ram 3500 Regular C&C'),
  array('ModelId'=>'12541','DisplayName'=>'Sierra 3500 HD Regular Cab & Chassis','Description'=>'','MakeId'=>'16','SortOrder'=>'90','MarketName'=>'Sierra 3500','ShortName'=>'Sierra 3500 HD Reg C&C'),
  array('ModelId'=>'12549','DisplayName'=>'Silverado 3500 HD Extended Cab & Chassis','Description'=>'','MakeId'=>'9','SortOrder'=>'112','MarketName'=>'Silverado 3500','ShortName'=>'Silverado 3500HD Ext C&C'),
  array('ModelId'=>'12554','DisplayName'=>'R8','Description'=>'','MakeId'=>'4','SortOrder'=>'17','MarketName'=>'','ShortName'=>'R8'),
  array('ModelId'=>'27717','DisplayName'=>'Econoline E350 Cargo','Description'=>'','MakeId'=>'15','SortOrder'=>'26','MarketName'=>'Econoline','ShortName'=>'Econoline E350 Cargo'),
  array('ModelId'=>'27751','DisplayName'=>'3500 Regular Cab & Chassis','Description'=>'','MakeId'=>'16','SortOrder'=>'21','MarketName'=>'3500 Trucks','ShortName'=>'3500 Regular C&C'),
  array('ModelId'=>'27753','DisplayName'=>'3500 Crew Cab & Chassis','Description'=>'','MakeId'=>'16','SortOrder'=>'17','MarketName'=>'3500 Trucks','ShortName'=>'3500 Crew Cab & Chassis'),
  array('ModelId'=>'27767','DisplayName'=>'GS','Description'=>'','MakeId'=>'27','SortOrder'=>'4','MarketName'=>'','ShortName'=>'GS'),
  array('ModelId'=>'27807','DisplayName'=>'RX','Description'=>'','MakeId'=>'27','SortOrder'=>'25','MarketName'=>'','ShortName'=>'RX'),
  array('ModelId'=>'27820','DisplayName'=>'Express Cutaway','Description'=>'','MakeId'=>'9','SortOrder'=>'54','MarketName'=>'Express','ShortName'=>'Express Cutaway'),
  array('ModelId'=>'27855','DisplayName'=>'Sierra (Classic) 3500 HD Regular Cab & Chassis','Description'=>'','MakeId'=>'16','SortOrder'=>'65','MarketName'=>'Sierra (Classic) 3500','ShortName'=>'Sierra(Clsc)3500HD RegC&C')
);
